package smasini.it.traxer.enums;

/**
 * Created by Simone Masini on 16/04/2016.
 */
public enum UriQueryType {
    COUNT_ALL,
    COUNT_ALL_WATCH,
    COUNT_ALL_BY_SERIE,
    COUNT_ALL_SERIE,
    COUNT_ALL_TODAY,
    COUNT_SEASON_NUMBER,
    COUNT_SEASON_BY_SERIE,
    COUNT_SEASON_WATCH_BY_SERIE,
    TIME_SPENT_WATCH,
    EPISODE_MISS,
    EPISODE_NEXT_OUT,
    EPISODE_NEXT_OUT_TODAY,
    SEASONS_BY_SERIE,
    EPISODES_BY_SERIE_AND_SEASON,
    EPISODE_BY_ID,
    ALL_EPISODES_BY_SERIE,
    SERIE_WITH_ID,
    CAST_WITH_SERIEID,
    ACTOR_WITH_ID,
    NEXT_EPISODE_TO_WATCH
}
